### ISSUE TITLE
Libraries  are not working when if it got listed in pip

### ISSUE THREAD

**Issue by georgethomas08** [Azure/azure-iot-sdk-python#1143]
Hi team,

Please find the SS below, the library was working fine all of a sudden it shows no module, I have uninstalled and reinstalled again but no chance, all other libraries are working fine except this

![Screenshot from 2023-05-23 16-59-37](https://github.com/Azure/azure-iot-sdk-python/assets/8665537/f7e36351-122a-4c54-b6dd-5e61c568f08d)

**Comment by lev-i** [comment]
@georgethomas08

It looks like you might be using V3 of the SDK instead of V2? V3 switches to `from azure.iot.device import IoTHubSession` instead of `from azure.iot.device.aio import IoTHubDeviceClient`.

The guide [here](https://github.com/Azure/azure-iot-sdk-python/blob/main/migration_guide_iothub.md) has more info if you're interested, and the updated samples have some usage examples. If you want you can post the files and we can take a closer look.
