### ISSUE TITLE
Sample code for setting content type and encoding

### ISSUE THREAD

**Issue by apcsaba** [Azure/azure-iot-sdk-python#138]
Can you please provide a sample code demonstrating how to set the message content type and encoding using python sdk?
I am trying to achieve "IoT Hub message routing with routing on message body "and I am looking for a simple python code for constructing the message body and content type in the correct format similar to what is described in [this link](https://azure.microsoft.com/en-us/blog/iot-hub-message-routing-now-with-routing-on-message-body/). Thank you.

**Comment by zolvarga** [comment]
@apcsaba 

Here is the sample code:

setContentResult = message.set_content_encoding_system_property("utf-8")
if (setContentResult != 0):
                print ( "set_content_encoding_system_property failed" )
                break

setContentTypeResult = message.set_content_type_system_property("application/json")
if (setContentTypeResult != 0):
                print ( "set_content_type_system_property failed" )
                break

Best Regards,
Zoltan

**Comment by janickat24** [comment]
I modified SimulatedDevice.py to set the content type and content encoding as described above:
```python
message = IoTHubMessage(msg_txt_formatted)
set_content_result = message.set_content_encoding_system_property("utf-8")
set_content_type_result = message.set_content_type_system_property("application/json")

if set_content_result != 0:
    print("set_content_encoding_system_property FAILED")
            
if set_content_type_result != 0:
    print("set_content_type_system_property FAILED")
```
I have also set the sleep timer to 1000 seconds because I noticed that I was not receiving a response from the IoT hub. After some time has passed I get the following response:

```
Sending message: {"temperature": 20.52,"humidity": 67.88}
IoT Hub responded to message with status: MESSAGE_TIMEOUT
```
I am not seeing any incoming messages to the event hub using the device explorer tool. However if I don't set the content type and content encoding the messages send.

Not sure if this is relevant but I also receive these two error messages when running the script with or without the content settings:
```
Error: Time:Tue Jul 10 16:00:40 2018 File:/usr/sdk/src/c/iothub_client/src/iothub_client_core_ll.c Func:IoTHubClientCore_LL_CreateFromConnectionString Line:892 iotHubName is not found
Error: Time:Tue Jul 10 16:00:40 2018 File:/usr/sdk/src/c/iothub_client/src/iothub_client_core.c Func:create_iothub_instance Line:928 Failure creating iothub handle
```
I have been ignoring it because the messages were still sending and being acknowledged by the IoT hub.

**Comment by pierreca** [comment]
@janickat24 it's bizarre because the error you're seeing indicates it might not find the IoT hub (which means no matter how much you change message properties, it shouldn't work).

One thing that might be related: there's a bug in the C SDK that requires an additional call to make sure the content-type property is picked up correctly if you are using MQTT: see https://github.com/Azure/azure-iot-sdk-python/issues/153

Hope that helps - and if it doesn't, feel free to open a new issue, showing us in detail your code, the console logs, what protocol you're using, and what you are observing. thanks!

**Comment by janickat24** [comment]
Added `client.set_option("auto_url_encode_decode", True)` to the `iothub_client_init()` function and everything seems to be working correctly. Thanks!

**Comment by pierreca** [comment]
@janickat24 thanks for confirming! glad to hear that!
