### ISSUE TITLE
Grouping device-to-cloud messages into batches

### ISSUE THREAD

**Issue by ahirner** [Azure/azure-iot-sdk-python#15]
The documentation says batching is possible for up to 256KB (https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-messaging). However, I can't find the right endpoint in the preliminary API nor in the REST documentation. The C# API has implemented such a call. Am I missing something?

**Comment by olivierbloch** [comment]
Hi @ahirner 
The C and Python SDKs (Python SDK happens to be a wrapper on top of the C SDK) have a slightly different behavior when it comes to batching than the C# one.
The C SDK, and hence the Python one, will implement batching automatically and using an "optimistic" mechanism.
In order to enable the batching in the C or Python SDK, you need to use the SetOption API (IoTHubClient_SetOption in C) and set the "Batching" option to true or false.

Now here is how things work under the hood (that will explain the difference in behavior compared to the C# SDK):
I will not go into the details of the Lower Level API vs. convenience API here as it is described in [this article](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-device-sdk-c-iothubclient), but it is important to understand the basics of how things work in the C SDK.
The underlying mechanism of the C SDK is that message sends are queued and effectively sent over the wire when the DoWork function runs. Depending on the "Batching" option flag messages will be sent as individual ones or as a single batched message at that moment DoWork is called.
When using the Lower Level API in C, the user triggers the DoWork manually, meaning he can have full control on when the batch send is called, but when using the convenience layer of the API, the DoWork is periodically called behind the scenes by the SDK itself and the user basically cannot dine control the granularity of the batches.
The Python SDK only exposes the convenience layer, meaning that you can enable the batching, but you cannot control exactly when the DoWork is invoked, hence you cannot control the granularity of the batches.

**Comment by ahirner** [comment]
Hi @olivierbloch,
This is a very helpful explanation. So enabling Batching in the convenience APIs optimizes for throughput on HTTP, whereas disabling optimizes for latency. I think this is a reasonable design choice. 
The article also clarifies how many messages get batched up (max size, i.e. 256KB). I suppose flushing the queue earlier when switching from enabled to disabled happens upon the next send message and not upon resetting the Batching option. Correct me if I have this wrong. Again, very helpful!

**Comment by olivierbloch** [comment]
@ahirner 
I would have to double check in the code, but I would say that if you reset the batching option while messages are in the queue, then next time DoWork is invoked then the method set by the flag is applied, meaning that for example if you had messages in the queue and the batching flag set to true and you switch to false, then when DoWork is invoked then messages will be sent individually even though they were queued while the flag was set to true.

**Comment by ahirner** [comment]
@olivierbloch This behaviour would also make sense if queued vs single messages go through different endpoints. It seems to me though, that both code paths make the same call and maintain separate buffers (temp for batched, toBeSend for unbatched). So switching the Batching option pauses the respective alternative queue if there is no other codepath where messages get dispatched (I was only skimming https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/src/iothubtransporthttp.c#L1565). But I'm not sure either. If that's the case, exposing DoWork to convenience APIs as makes sense for devices that send high/low-latency data interleaved.

**Comment by olivierbloch** [comment]
@ahirner 
There is only one endpoint where D2C messages go whether batched or not. IoTHub will decipher messages showing as batches and will split them into individual messages for consumption by Cloud services.
I am not the expert of this code, but my reading tells me there is a single queue for messages independently of the Batching flag.
The ```DoEvent``` function (which is called by ```DoWork``` to deal with sending queued messages) gets the messages from ```deviceData->waitingToSend``` which is the queue of messages to be sent (independently of whether batching is set or not) and constitutes the payload for batching or sends individual request for each messages in ```deviceData->waitingToSend```.

**Comment by ahirner** [comment]
@olivierbloch Thanks for pointing out the shared queue. The behaviour mentioned before makes sense if the IoTHub figures out the unpacking. I'll go from there and implement switching back to unbatched mode as late as possible. This should make sure most low-latency messages get batched up.

**Comment by olivierbloch** [comment]
Cool, Ill go ahead and close this thread then.
Let us know if you face other issues or have other questions
