### ISSUE TITLE
Provisioning Device Client - Device Registration failed

### ISSUE THREAD

**Issue by Bnjmn83** [Azure/azure-iot-sdk-python#177]
So I created a new Root Cert using this guide https://github.com/Azure/azure-iot-sdk-c/blob/master/tools/CACertificates/CACertificateOverview.md and added/verified it on DPS and on my IoT Hub. I created an enrollment group and assigned my Root Cert to it. I modifid the _azure-iot-sdk-python\provisioning_device_client\samples\provisioning_device_client_sample.py_ file to match my Global device endpoint and my ID scope. The device shows up in my Hub's IoT device list and says SelfSigned and enabled. Anyway the result of the provisioning script say _Device Registration failed_:

```
...
Register status callback:
reg_status = ASSIGNING
user_context = None

GET /0ne00023C3C/registrations/riot-device-cert/operations/4.87f7851aaaa18ed1.df81c879-7e0e-4529-bbdd-d492b98c21df?api-version=2017-11-15 HTTP/1.1
UserAgent: prov_device_client/1.0
Accept: application/json
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Host: global.azure-devices-provisioning.net:443
content-length: 0



HTTP Status: 200

date: Thu, 16 Aug 2018 11:36:30 GMT
content-type: application/json; charset=utf-8
transfer-encoding: chunked
x-ms-request-id: f4cdfbde-3e7b-4e8d-82ae-b55e1f597e57
strict-transport-security: max-age=31536000; includeSubDomains

{"operationId":"4.87f7851aaaa18ed1.df81c879-7e0e-4529-bbdd-d492b98c21df","status":"assigned","registrationState":{"x509":{},"registrationId":"riot-device-cert","createdDateTimeUtc":"2018-08-16T11:36:28.2215622Z","assignedHub":"Bens-IoT-Hub.azure-devices.net","deviceId":"riot-device-cert","status":"assigned","lastUpdatedDateTimeUtc":"2018-08-16T11:36:28.3993492Z","etag":"\u002203008b4b-0000-0000-0000-5b7561bc0000\u0022"}}


Register device callback:
   register_result = OK
   iothub_uri = Bens-IoT-Hub.azure-devices.net
   user_context = None
   device_id = riot-device-cert

Device successfully registered!

Error: Time:Thu Aug 16 13:38:31 2018 File:C:\release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\provisioning_client\src\prov_transport_http_client.c Func:on_http_error Line:113 http error encountered: HTTP_CALLBACK_REASON_ERROR
Error: Time:Thu Aug 16 13:38:31 2018 File:C:\release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\provisioning_client\src\prov_device_ll_client.c Func:on_transport_registration_data Line:455 Failure retrieving data from the provisioning service

Register device callback:
   register_result = TRANSPORT
   iothub_uri = None
   user_context = None
   device_id = None

Device registration failed!
```
Here's the CN label of my certificate (all lower case):

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            ef:fd:f9:be:da:50:ac:f9
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=azuretestcert
        Validity
            Not Before: Aug 16 10:52:30 2018 GMT
            Not After : Sep 15 10:52:30 2018 GMT
        Subject: CN=azuretestcert
```

- Win10 Enterprise
- Python 3.6.6
- Provisioning API Version: 1.2.8

**Comment by Bnjmn83** [comment]
I'd love to but I am stuck there as well: https://github.com/Azure/azure-iot-sdk-python/issues/186 . For the provisiong procedure HTTP is fine?

Also I do have a question regarding this process. So I do now have 10 devices all being based on the sample code from here _azure-iot-sdk-python\provisioning_device_client\samples\provisioning_device_client_sample.py_. In the DPS there are 5 enrollment groups all setup with a different certificate. How does the DPS know which device to register via which enrollment group? I mean the device's code is generic. No connection to a certificate whatsoever. Please clarify. Thanks.

**Comment by Bnjmn83** [comment]
I could make it work using the C# example though, but not in Python or in C. Can someone please point me to the interfaces I need to provide my leaf pfx file as well as the intermediate certificate to register my device using Group Enrollment.

**Comment by anhashia** [comment]
You can use 
https://github.com/Azure/azure-iot-sdk-python/blob/master/provisioning_device_client/samples/provisioning_device_client_sample.py
for both individual and group enrollment.

This is for demonstration purpose and is tied to test certs generated from sample **tool**
https://github.com/Azure/azure-iot-sdk-python/blob/master/provisioning_device_client/doc/using_group_enrollment_dice.md

**dice_device_enrollment**

Sample cert chain from this tool is  like this
riot-root->riot-signer-core->riot-device-cert

For using your own custom certs, you can track https://github.com/Azure/azure-iot-sdk-c/issues/635. Looks like you already tracking that also :-)

**Comment by itslasya** [comment]
I have used open ssl to generate the certificate, instead of using visual studio,
logs:
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)]
Provisioning Device Client for Python
Starting the Provisioning Client Python sample...
    Scope ID=0nexxxxxxx
    Security Device Type X509
    Protocol HTTP

Provisioning API Version: 1.2.12

Press Enter to interrupt...

Register status callback:
reg_status = CONNECTED
user_context = None

PUT /0ne00060B3E/registrations/riot-device-cert/register?api-version=2018-09-01-preview HTTP/1.1
UserAgent: prov_device_client/1.0
Accept: application/json
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Host: global.azure-devices-provisioning.net:443
content-length: 39
len: 39
{ "registrationId":"riot-device-cert" }


HTTP Status: 401

date: Mon, 10 Jun 2019 10:50:14 GMT
content-type: application/json; charset=utf-8
transfer-encoding: chunked
x-ms-request-id: 5b6ff496-03bd-454b-8038-1a32f8504be8
strict-transport-security: max-age=31536000; includeSubDomains

{"errorCode":401002,"trackingId":"5b6ff496-03bd-454b-8038-1a32f8504be8","message":"Invalid certificate","timestampUtc":"2019-06-10T10:50:14.7793152Z"}

Error: Time:Mon Jun 10 16:20:15 2019 File:C:\Release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\provisioning_client\src\prov_device_ll_client.c Func:prov_transport_process_json_reply Line:323 failure retrieving json auth key value
Error: Time:Mon Jun 10 16:20:15 2019 File:C:\Release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\provisioning_client\src\prov_transport_http_client.c Func:prov_transport_http_dowork Line:941 Unable to process registration reply.
Error: Time:Mon Jun 10 16:20:15 2019 File:C:\Release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\provisioning_client\src\prov_device_ll_client.c Func:on_transport_registration_data Line:572 Failure retrieving data from the provisioning service

Register device callback:
   register_result = PARSING
   iothub_uri = None
   user_context = None

Device registration failed!

**Comment by az-iot-builder-01** [comment]
@Bnjmn83, @anhashia, @itslasya, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
