### ISSUE TITLE
Alpine installation

### ISSUE THREAD

**Issue by botasb** [Azure/azure-iot-sdk-python#199]
Hi,
I need to install azure-iot-sdk-python in a Raspberry Pi 3 with and alpine distro. I can't find a way to do it. Any experience there?
In fact, I need to install it in a Raspberry Pi 3 running a container with this docker image:
homeassistant/raspberrypi3-homeassistant

Thanks a lot.

**Comment by pierreca** [comment]
@botasb 
alpine is not part of the distros we're testing with, so I'm not sure how to install the required dependencies. (the proper version of boost-python, curl, libssl, etc). 

which wheel file is dowloaded when you pip install our package?

**Comment by pierreca** [comment]
@botasb 
FYI I've created a "dockerfiles" folder in the repository so that we can share the container configs we build and test the SDK with, as well as for others to submit PRs if they want to share how to make other base images work. might be worth monitoring or contributing to if you've solved the problem.

Given we're reworking the SDK to not take a dependency on external C things (that's a long-term goal), it's unlikely we will address alpine dependency install/support with this version of the SDK so I'm going to close this issue. however if anyone feels like contributing this to the dockerfiles folder, we'll gladly accept the PR.

**Comment by az-iot-builder-01** [comment]
@botasb, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
