### ISSUE TITLE
Upload requires full file to be loaded into memory

### ISSUE THREAD

**Issue by andrewschmidt-a** [Azure/azure-iot-sdk-python#202]
Currently in the IoT SDK for Python there is a file upload capability. 
This feature requires that the file be loaded completely into memory which can be impossible for boards that have lower specs for memory.

It would be great if it were possible to upload BlockBlobs and be able to define the block size.

See below example
[BlockBlob_example.zip](https://github.com/Azure/azure-iot-sdk-python/files/2406624/BlockBlob_example.zip)

**Comment by pierreca** [comment]
@andrewschmidt-a definitely something we could look into long-term, given the only thing IoT Hub does is broker a shared access signature for a container for that specific device. this being said, this investment is likely going to be in the v2 of the SDK that is a few weeks, if not months out (Work for a complete rewrite entirely in python rather than as a C SDK wrapper is just starting)

**Comment by jebrando** [comment]
With the Python v2 reaching General Availability we are recommending users move away from the v1 SDK. 
We will be closing the v1 SDK issues whose features are covered by the v2 release. 
Feel free to open an new issue if you find an issue with the v2 SDK.
 
Thank you for your patronage

**Comment by az-iot-builder-01** [comment]
@andrewschmidt-a, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
