### ISSUE TITLE
Request for ARM64v8/aarch64 build of the SDK

### ISSUE THREAD

**Issue by FluxReality** [Azure/azure-iot-sdk-python#232]
- **OS and version used:** Linux tegra-ubuntu 4.4.38-tegra aarch64

- **Python runtime used:** 2.7 and 3.6

- **SDK version used:** 1.4.4

# Description of the issue:
Trying to build a docker module based of the [arm64v8/debian:stretch](https://hub.docker.com/r/arm64v8/debian/) docker image, To run on a **Nvidia Jetson Tegra TX2** device. When building the image and running the `pip install azure-iothub-device-client` i get the pip install error "`Could not find a version that satisfies the requirement azure-iothub-device-client==1.4.4`" 

I suppose this is due to the fact that there hasn't been built any release of the Python SDK for **ARM64/aarch64** yet. So I guess this is more a request for it to be built and available through the regular PIP channel if possible.

# Code sample exhibiting the issue:
pip install azure-iothub-device-client==1.4.4

# Console log of the issue:
```
Collecting azure-iothub-device-client==1.4.4 (from -r requirements.txt (line 1))
  Could not find a version that satisfies the requirement azure-iothub-device-client==1.4.4 (from -r requirements.txt (line 1)) (from versions: )
No matching distribution found for azure-iothub-device-client==1.4.4 (from -r requirements.txt (line 1))
The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1
```

**Comment by pierreca** [comment]
@FluxReality That's highly unlikely to happen with the current version of the SDK. We're focusing on rewriting a new version that will be a pure-python implementation instead of a wrapper over the C SDK and should support arm64. The current, wrapper-based implementation will only see bugfixes but not enhancements or new platforms support.

We do have a [build guide](https://github.com/Azure/azure-iot-sdk-python/blob/master/doc/python-devbox-setup.md) so if someone wants to try and setup a build for arm64 architectures, we'd be happy to share the dockerfile in this repository, as part of our dockerfiles folder. 

We do hope to have a preview of the v2 SDK very soon. it will support only MQTT at first, and we will progressively roll out features (starting with telemetry, cloud-to-device messages & input/output channels for Azure IoT Edge). If you have suggestions about how to prioritize features for the new version, we're all ears.

**Comment by az-iot-builder-01** [comment]
@FluxReality, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
