### ISSUE TITLE
Passing a device certificate to provisioning client on linux

### ISSUE THREAD

**Issue by mathias-nickl** [Azure/azure-iot-sdk-python#254]
Hi there! 

I am trying to provision devices with the python provisioning sdk on a linux machine. However I am not able to pass the device certificate to the provisioning client. In C# the provisioning client provides a parameter to pass the certificate via a security provider. But I am struggling to build an equivalent example in python.

How can I pass the device certificate to the provisioning device client in python?  

Best 

Mathias

- OS and version used: Ubuntu 15.04

- Python runtime used: 3.6

**Comment by 1-Peter** [comment]
Hi,

we are struggeling with a similar problem.
Any advice would be apprreciated.

Kind Regards
M. Peter

**Comment by pierreca** [comment]
@mathias-nickl @1-Peter unfortunately i have no satisfying answer for now:

Because the current SDK is built on the C SDK, the way to do this is to implement a custom HSM module. See:
https://github.com/Azure/azure-iot-sdk-c/blob/master/provisioning_client/devdoc/using_custom_hsm.md

This entails developing a custom HSM module in C, then rebuilding the C+Python SDK while linking to the HSM module.

we're absolutely conscious of the fact that this is not a good python experience which is why we're working on a new implementation of the SDK that doesn't rely on the C SDK ([here](https://github.com/azure/azure-iot-sdk-python-preview)) rather than investing in trying to patch this version of the SDK, given this design obviously doesn't work for 99% of users.

**Comment by pierreca** [comment]
I believe we've responded to this question in #272 : the new v2 client deals with certificate a lot better than v1.

**Comment by az-iot-builder-01** [comment]
@mathias-nickl, @1-Peter, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
