### ISSUE TITLE
Host images on dockerhub

### ISSUE THREAD

**Issue by david-mcgillicuddy-ovo** [Azure/azure-iot-sdk-python#257]
The included Dockerfiles are great, and make a tricky install much easier. Is there a reason these python images are not hosted on microsoft's dockerhub account? The closest I could find were the C# client sdk images: https://hub.docker.com/_/microsoft-iotedge-iotedgedev

**Comment by pierreca** [comment]
At that point, probably just because we're in the process of rewriting this SDK and that the future version will be so much simpler to install.

Also, for Azure IoT SDKs to get on the official microsoft dockerhub account, we'd have to come up with a strategy that address all the languages we cover. while we've talked about this internally, we haven't been able to address it due to other high priority items.

**Comment by az-iot-builder-01** [comment]
@david-mcgillicuddy-ovo, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
