### ISSUE TITLE
Unexpected error module 'socket' has no attribute 'AF_UNIX' on Windows

### ISSUE THREAD

**Issue by blackchoey** [Azure/azure-iot-sdk-python#287]
I tried to run a module on  a Windows Edge device and got following error when my module starts. Could anyone help on this error?
Error: `Unexpected error module 'socket' has no attribute 'AF_UNIX'`
Here's my SampleModule code: [https://github.com/blackchoey/IoTEdgePythonSDKPreview](https://github.com/blackchoey/IoTEdgePythonSDKPreview)
I followed this [tutorial](https://docs.microsoft.com/en-us/azure/iot-edge/quickstart#install-and-start-the-iot-edge-runtime) to setup iotedge runtime on windows

AB#7366696

**Comment by elhorton** [comment]
Hi Python community, we are going to close this issue since we have no plans to support Unix domain sockets in the Python SDK. The official guidance from IoT Edge is to use [Linux containers](https://techcommunity.microsoft.com/t5/internet-of-things/linux-modules-with-azure-iot-edge-on-windows-10-iot-enterprise/ba-p/1407066) on Windows devices. IoT Edge on Python is scoped to Linux and is documented [on this page](https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-python-module#solution-scope).

**Comment by az-iot-builder-01** [comment]
@BertKleewein, @blackchoey, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
