### ISSUE TITLE
find_package fails for python 3

### ISSUE THREAD

**Issue by hassler** [Azure/azure-iot-sdk-python#30]
- **OS and version used:** Ubuntu 15.04 as host 

- **Python runtime used:** Python 3.4 

- **SDK version used:** master 2017 maj 09 

# Description of the issue:
When cross-compiling find_package does not find libs for boost python3
including my ugly fix for the issue to clarify.
```
 --- a/device/iothub_client_python/CMakeLists.txt
+++ b/device/iothub_client_python/CMakeLists.txt
         string(REPLACE "." "" boost_python ${build_python})
-        find_package(Boost COMPONENTS "python-py${boost_python}")
+        find_package(Boost COMPONENTS "python3")

--- a/service/CMakeLists.txt
+++ b/service/CMakeLists.txt
         string(REPLACE "." "" boost_python ${build_python})
-        find_package(Boost COMPONENTS "python-py${boost_python}")
+        find_package(Boost COMPONENTS "python3") 
```

# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by ewertons** [comment]
Hi @hassler ,

you don't need to modify the cmake file when compiling. 
The reason why it searches for a concatenated string is because we allow compiling against different versions of python boost.

A typical python2 and python3 installation would look like:

```
$ ls -l /usr/bin/python*
lrwxrwxrwx 1 root root       9 Oct 19  2016 /usr/bin/python -> python2.7
lrwxrwxrwx 1 root root       9 Oct 19  2016 /usr/bin/python2 -> python2.7
-rwxr-xr-x 1 root root 3546104 Nov 19 01:35 /usr/bin/python2.7
...
lrwxrwxrwx 1 root root       9 Oct 19  2016 /usr/bin/python3 -> python3.5
-rwxr-xr-x 2 root root 4460336 Nov 17 11:23 /usr/bin/python3.5
...
```

So one builds using 
```
~/azure-iot-sdk-python/build_all/linux$./build.sh --build-python 3.5
```
it would find python3.5 since it is set as such above.

If you are building against python3.4, could you confirm you have python3.4 in your /usr/bin (or any other location where you might have installed it, making sure it is reachable from the path where you are building the solution)?

**Comment by tameraw** [comment]
@hassler - Please feel free to reopen if still having issues.
