### ISSUE TITLE
Can't load any of the usual classes from iothub_client module but no complains when I try to load all (from iothub_client import *) but I still miss the classes

### ISSUE THREAD

**Issue by Nojahhh** [Azure/azure-iot-sdk-python#326]
Hey guys,

Idk if I'm dumb and missed any ongoing rework of this SDK since I can see you are working with it even as we speak but I can't manage to load any of my usual classes I've used with this SDK before.

trying to load
´from iothub_client import IoTHubClient, IoTHubClientError, IoTHubTransportProvider 
from iothub_client import IoTHubMessage, IoTHubMessageDispositionResult, IoTHubError, DeviceMethodReturnValue´
just results in
´No name 'IoTHubClient' in module 'iothub_client'pylint(no-name-in-module)
No name 'IoTHubClientError' in module 'iothub_client'pylint(no-name-in-module)
No name 'IoTHubTransportProvider' in module 'iothub_client'pylint(no-name-in-module)´

I'm pretty sure I've got all the dependencies needed for this module but I might be wrong. Anyone got any suggestions?

**Comment by Nojahhh** [comment]
forgot the other ones as well
´No name 'IoTHubMessage' in module 'iothub_client'pylint(no-name-in-module)
No name 'IoTHubMessageDispositionResult' in module 'iothub_client'pylint(no-name-in-module)
No name 'IoTHubError' in module 'iothub_client'pylint(no-name-in-module)
No name 'DeviceMethodReturnValue' in module 'iothub_client'pylint(no-name-in-module)´

**Comment by olivakar** [comment]
From the imports it looks like this is the Version 1 of the SDK. 
The one we are currently working on is Version 2. 
We have officially deprecated V1 at this time, in order to focus on the V2 implementation.

If you have worked with the Version 1 before then the Version 1 should work as it used to. 

However if you are trying to install the V2 then the install is 
`pip install azure-iot-device`

And the imports for synchronous client is 
`from azure.iot.device import IoTHubDeviceClient`
And for asynchronous client is
`from azure.iot.device.aio import IoTHubDeviceClient`

**Comment by Nojahhh** [comment]
Thanks a lot @olivakar , that's most probably it, haven't been able to confirm yet but i'm pretty sure it is.

And thanks for such a quick reply! Gonna go ahead and close this :)

**Comment by az-iot-builder-01** [comment]
@Nojahhh, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
