### ISSUE TITLE
Error while sending device to cloud Messages  

### ISSUE THREAD

**Issue by arnabhetc** [Azure/azure-iot-sdk-python#332]
I am trying to connect and send message to IoT Hub using new SDK -->

https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-device/samples/legacy-samples/send_message.py

[this](https://textuploader.com/1ka4x) is the error I am getting, 

I am using MAC OS; this is working perfectly on ubuntu 16.04!

**Comment by antoinebouchard1** [comment]
Same error here but using the following example code:

```
async def send_test_message():
    # Create instance of the device client using the connection string
    device_client = IoTHubDeviceClient.create_from_connection_string(CONNECTION_STRING)

    # Send a single message
    print("Sending message...")
    await device_client.send_message("This is a message that is being sent")
    print("Message successfully sent!")

    # finally, disconnect
    await device_client.disconnect()
```


Also getting 

`ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)
`
which seems to be caused by paho:

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/.../venv/lib/python3.7/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 29, in handle_result
    return await callback.completion()
  File "/.../venv/lib/python3.7/site-packages/azure/iot/device/common/async_adapter.py", line 93, in completion
    return await self.future
  File "/.../venv/lib/python3.7/site-packages/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py", line 100, in _execute_op
    self.transport.connect(password=self.sas_token)
  File "/.../venv/lib/python3.7/site-packages/azure/iot/device/common/mqtt_transport.py", line 255, in connect
    message="Unexpected Paho failure during connect", cause=e
azure.iot.device.common.transport_exceptions.ProtocolClientError: Unexpected Paho failure during connect
```

This is under macOS 10.14.6, using paho-mqtt 1.4.0
Haven't tested under Ubuntu

**Comment by olivakar** [comment]
You are using connection string and this sample is working on Ubuntu..
So from the error it seems like an issue that is specific to Mac OS.

I think this is an issue with the openssl install that comes bundled with python and the way python was installed on mac.

You can try 2 things in order of preference

- `pip install --upgrade certifi` 
- `open /Applications/Python\ 3.7/Install\ Certificates.command`

**Comment by arnabhetc** [comment]
@olivakar  fixed my issue, Thanks a lot

**Comment by az-iot-builder-01** [comment]
@antoinebouchard1, @arnabhetc, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by JesseJ12345** [comment]
I also met this problem, the info shows as follows, 
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    device_client.connect()
  File "<string>", line 1, in connect
  File "/var/user/lib/python3.7/site-packages/azure/iot/device/iothub/sync_clients.py", line 116, in connect
    handle_result(callback)
  File "/var/user/lib/python3.7/site-packages/azure/iot/device/iothub/sync_clients.py", line 43, in handle_result
    message="Error in the IoTHub client due to TLS exchanges.", cause=e
azure.iot.device.exceptions.ClientError: ClientError('Error in the IoTHub client due to TLS exchanges.') caused by TlsExchangeAuthError(None)

**Comment by zeeshan-mehdi** [comment]
pip install --upgrade certifi
open /Applications/Python\ 3.9/Install\ Certificates.command

worked for me. i had python 3.9 installed.
