### ISSUE TITLE
receive_message.py: Exception ProtocolClientError: Out of memory

### ISSUE THREAD

**Issue by HoLue** [Azure/azure-iot-sdk-python#370]
Hello!

I tried
`azure-iot-sdk-python-master\azure-iot-device\samples\advanced-hub-scenarios\receive_message.py
`
on a Windows 10 machine. It starts, 
`Press Q to quit`
but when I dend a message the following output appears in the terminal:
```
MQTTTransportStage: _on_mqtt_disconnect called: Out of memory.
MQTTTransportStage: disconnection was unexpected
Exception caught in background thread.  Unable to handle.
azure.iot.device.common.transport_exceptions.ProtocolClientError: Out of memory.

The above exception was the direct cause of the following exception:

azure.iot.device.common.transport_exceptions.ConnectionDroppedError: None       
Connection was unexpected
```
I tried 2 different ways to send the messge with the same result.
First way on windows 10 machine using SimulatedDevice.py from https://github.com/Azure-Samples/azure-iot-samples-python:
`azure-iot-samples-python-master\iot-hub\Quickstarts\simulated-device\SimulatedDevice.py
`
Second way on Raspberry Pi from https://github.com/Azure/azure-iot-sdk-python-preview/blob/master/azure-iot-device/samples/README.md
`simple_telemetry.py`

What can I do? Please help!

**Actually I want to implement a communication between Cloud (IoT hub) and the device in python. Any way to get this worked will be great!!**

**Comment by olivakar** [comment]
I have ran the [receive_message.py](https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-device/samples/advanced-hub-scenarios/receive_message.py) sample in the `advanced-hub-scenarios` and it works fine. This is the scenario of a C2D (cloud to device) message. The output of a run with 2 C2D (cloud to device) messages that were sent to the device is shown below. 

```
Press Q to quit
the data in the message received was 
b'hi'
custom properties are
{}

the data in the message received was 
b'weather report'
custom properties are
{'temp': '42'}

Press Q to quit
Q
Quitting...

Process finished with exit code 0
```
**For this sample from where are you trying to send message ?** 

==============================================================
The second example of  [SimulatedDevice.py](https://github.com/Azure-Samples/azure-iot-samples-python/blob/master/iot-hub/Quickstarts/simulated-device/SimulatedDevice.py) is meant for V1 of the python SDK.  **So which version of the SDK are you using ?**

==============================================================

The third example of `simple_telemetry.py` is actually the same sample as  [simple_send_message.py](https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-device/samples/simple_send_message.py) and this also runs fine for me. The output of such a run is 

```
Sending message...
Message successfully sent!

Process finished with exit code 0
```

Please make sure you have the correct connection string.

**Comment by HoLue** [comment]
Thanks for your answer!!

The samples SimulatedDevice.py and simple_telemetry.py worked.
And I misunderstood the receive_message.py. When I send a message via Cloud Shell
`az iot device c2d-message send --device-id <your device id> --hub-name <your IoT Hub name> --data <your message here>`
I can receive the message - great! Nevertheless I am astonished that when I send a message from that device via SimulatedDevice.py or simple_telemetry.py that the errors are given which I described in my first post.

**Actually I'm looking for a way to receive messages from a device (IoT). How can I do that (by code, not by Cloud Shell)?**

(And one more question: How can I find out if I use V1 or V2?)

**Comment by olivakar** [comment]
For any feature meant for device the V2 samples are all here in this repo itself.  Please have a look at the [this samples folder](https://github.com/Azure/azure-iot-sdk-python/tree/master/azure-iot-device/samples).
To be more specific , the sync scenarios are here [legacy scenarios](https://github.com/Azure/azure-iot-sdk-python/tree/master/azure-iot-device/samples/legacy-samples)
The async scenarios are here [advanced scenarios](https://github.com/Azure/azure-iot-sdk-python/tree/master/azure-iot-device/samples/advanced-hub-scenarios)

When you opened the samples from the [azure-iot-sdk-python-preview](https://github.com/Azure/azure-iot-sdk-python-preview) repo please keep in mind that `preview` repo is archived and the code from `preview` has officially moved to [azure-iot-sdk-python](https://github.com/Azure/azure-iot-sdk-python) where the issues are getting reported.

Our V2 is currenlty available via pip. The pypi link is [here](https://pypi.org/project/azure-iot-device/)

================================================================

In regards to looking for a way to receive messages from device I am not exactly sure what you mean. But I will give you 2 scenarios which may help you. In order to do these you will need [Azure IoT Explorer](https://docs.microsoft.com/en-us/azure/iot-pnp/howto-install-iot-explorer)

1. You can send telemetry or messages (D2C) from your simulated device and see it on the Azure IoT Explorer. This is for samples like `SimulatedDevice.py` or `simple_send_message.py `
2. You can send C2D messages from Azure IoT Explorer and watch it on your console. This is for samples like `receive_message.py`.

================================================================

The biggest difference between V1 and v2 when you look at a sample is to check the import.
If the import looks like `from azure.iot.device.aio import IoTHubDeviceClient`
OR  `from azure.iot.device import IoTHubDeviceClient` then you are importing the V2 `deviceclient.`

if it looks like `import iothub_service_client` it is most probably V1.

Some of the samples in the [samples repo](https://github.com/Azure-Samples/azure-iot-samples-python) have been changed to use V2.  And I see that `SimulatedDevice.py` is a V2 sample but just to be more sure it is still safer to check the samples folder in this repo (first link in this comment)

**Comment by HoLue** [comment]
Thanks!
Please lt me divide like you:

Thanks! (Device features)

==============================================================
Send Messages to Device (C2D)
Well IoT Explorer is a way (thanks, I tried it). 

But how can I implement the following scenario:
D2C: send some values 
These values should be processed in a funcion app and the result should be send back to the device (C2D) e.g. to do something like shooting an image.


==============================================================
V1 / V2 Thanks

**Comment by Aaron-KBI** [comment]
I am encountering the same exact out of memory error using my own code to send messages to my IoT Hub.
On the same IoT Hub, using my same code, and with two different IoT Hub enabled devices, one device can connect and send messages successfully, while the may (or may not) throw this error. There are days a device connects and sends messages successfully, and days it will not. With no changes to the code.

On my Pi, if I make no changes to the code other than device configuration (device name, cert, key), one device will produce the error while the other does not. I am led to believe that it might have something to do with the connection to the IoT Hub. Leaving the connection function and removing the send message function in my code still produce the error.

**Comment by Aaron-KBI** [comment]
> I am encountering the same exact out of memory error using my own code to send messages to my IoT Hub.
> On the same IoT Hub, using my same code, and with two different IoT Hub enabled devices, one device can connect and send messages successfully, while the may (or may not) throw this error. There are days a device connects and sends messages successfully, and days it will not. With no changes to the code.
> 
> On my Pi, if I make no changes to the code other than device configuration (device name, cert, key), one device will produce the error while the other does not. I am led to believe that it might have something to do with the connection to the IoT Hub. Leaving the connection function and removing the send message function in my code still produce the error.

I've figured it out. It was on my end. I had a background script connecting to my IoT Hub that was using the same IoT hub device as the script I was testing with. Running my script with the same device caused both of them to hit this out of memory error.

**Comment by olivakar** [comment]
https://github.com/Azure/azure-iot-sdk-python/issues/371#issuecomment-546543027

**Comment by az-iot-builder-01** [comment]
@HoLue, @Aaron-KBI, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
