### ISSUE TITLE
BackEndApplication.py: ImportError: DLL load failed

### ISSUE THREAD

**Issue by HoLue** [Azure/azure-iot-sdk-python#371]
Hello!

I tried
azure-iot-samples-python-master\iot-hub\Quickstarts\back-end-application\BackEndApplication.py
on a Windows 10 machine. The following error occurs:
```
Traceback (most recent call last):
  File "d:/DevIotAzure/azure-iot-samples-python-master/iot-hub/Quickstarts/back-end-application/BackEndApplication.py", line 9, in <module>    
    import iothub_service_client
  File "C:\Programme_Tools\Python\Python3_7_4_64bit\lib\site-packages\iothub_service_client\__init__.py", line 1, in <module>
    from .iothub_service_client import *
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.
```

What can I do? Please help!

**Actually I want to implement a communication between Cloud (IoT hub) and the device in python. Any way to get this worked will be great!!**

**Comment by olivakar** [comment]
This sample above is trying to use the version 1 of the python SDK. This is because of a dependency of the SDK on an external library called boost that only works with specific versions of python.

We have been working to release the version 2 of the python SDK. We have formally deprecated V1 at this time, in order to focus on the V2 implementation. There are already couple of features that are fully functional but most of them are on the device side.

However the feature in the `BackEndApplication.py` is for service client which has not yet been developed in the V2 of the python SDK. We hope to be able to offer a much better service client experience soon. In the meantime you'll have to stick to one of the few supported configurations.

There are couple of [dockerfiles](https://github.com/Azure/azure-iot-sdk-python/tree/v1-deprecated/dockerfiles) that can help you with that.

In case you are looking for anything else to do on the device side here is a link to our device [samples](https://github.com/Azure/azure-iot-sdk-python/tree/master/azure-iot-device/samples)

**Comment by HoLue** [comment]
Thanks for your answer!

Is there - without the dockerfiles - a possibility to react on a message from a device (function app? Trigered how?) by sending back an answer?

What is the time horizon for the 'much better service client experience'? A week? A month? A year?

**Comment by olivakar** [comment]
What you are looking for are the Cloud-to-device messaging from backend app and Direct Methods operations by using backend app.  And If you look at the [features for the service client ](https://github.com/Azure/azure-iot-sdk-python#iothub-service-library-azure-iot-hub) you can see neither of these are present in the V2 of the SDK. But these are present in V1 and the best way to get them working is using the dockerfiles. They have preconfigured environments that work with specific python version and boost verion.

As far as when the V2 is going to come up with these features I can't really absolutely say a time frame but may be there should be one of the features (C2D or Direct Methods) by end of year.

**Comment by HoLue** [comment]
@ olivakar
Thanks!

May you tell me something about the rough timeline of V2 for Cloud-to-device messaging? I would prefer using V2....

**Comment by HoLue** [comment]
@ olivakar
One more question - concerning the docker images - which docker should I take for a Azure serverless Function?

**Comment by olivakar** [comment]
The choice of the file depends on what python version you want and which operating system you have.

**Comment by HoLue** [comment]
@ olivakar
Sorry, that I don't understand.... When I want to use a Azure serverless function: Which docker file should I choose? Or does it depend on my development system? That's windows 10 and there are no docker files for windows 10....

**Comment by HoLue** [comment]
@ olivakar May you tell me something about the rough timeline of V2 for Cloud-to-device messaging? I would prefer using V2....

**Comment by jebrando** [comment]
@HoLue We are currently working on this issue and will report back on this as soon as we have a firm resolution.

**Comment by jebrando** [comment]
@HoLue We will be tracking the availability of the C2D messaging under item #458.  We will close this issue and refer to that issue for any updates.  Feel free to ask questions under that issue.

**Comment by az-iot-builder-01** [comment]
@HoLue, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
