### ISSUE TITLE
Connect() when system time is not (yet) set, corrupts IoTHubDeviceClient? V2.0.0

### ISSUE THREAD

**Issue by robbinvandamme** [Azure/azure-iot-sdk-python#448]
Steps to reproduce:

- set system time to 31/03/1987
- try to connect to IoTHub --> (Results in a "await connect()" that keeps retrying and never returns or never raises an exception.)
- set system time correct --> ("CredentialError" gets raised on the next retry. Here I expected that the "await connect()" would succeed?)
- call connect again on the same IoTHubClientDevice object --> (fails again with a "CredentialError" exception. IoTHubClientDevice object corrupted? Here I also expected that the "await connect()" would succeed?)
- restart application --> connection succeeds

[connect_when_system_time_is_wrong.txt](https://github.com/Azure/azure-iot-sdk-python/files/4132995/connect_when_system_time_is_wrong.txt)

**Comment by olivakar** [comment]
- set system time to 31/03/1987
- try to connect to IoTHub --> (Results in a "await connect()" that keeps retrying and never returns or never raises an exception.)

_For this connect, it actually retries as we are getting ssl certificate verify failed error from mqtt broker which is correct as the system time is behind. We may need to specifically look at this type of error to decide between retrying and not retrying._

**Comment by robbinvandamme** [comment]
@olivakar 
I don't have a problem with the fact that it is retrying. But the "await connect()" blocks forever, is that expected behavior? And when system time gets set correct, retrying stops and an exception is raised. Instead of the exception, I expected the connect() to succeed.

After the first connect(), that raised the exception when the system time got set correct, I tried to call connect() again. As you can see in the logs, the second connect() on the same object also fails, even when system time is correct. It seem like the IoTHubClientDevice got corrupted?

Restarting the application after the system time is correct, always works.

**Comment by olivakar** [comment]
- set system time correct --> ("CredentialError" gets raised on the next retry. Here I expected that the "await connect()" would succeed?)

_The first SSL error eventually gets converted into an Unauthorized error. I am still trying to figure out the reason for this conversion. But once we start getting Unauthorized  error, we actually raise an exception (**CredentialError**). Hence when the system time is getting set correct after some time the Connection is still not succeeding._

- call connect again on the same IoTHubClientDevice object --> (fails again with a "CredentialError" exception. IoTHubClientDevice object corrupted? Here I also expected that the "await connect()" would succeed?)

_This is the same behavior due to the above scenario._

**Comment by olivakar** [comment]
There are 2 errors getting raised here. 

1. The first one is a socket error (certificate failed) which is due to the mismatched times of the client and server.  We are thinking of raising an exception here when we get socket error caused from TLS exchange errors.

2. When the time eventually gets corrected and the connection is retried , it is still retried with a bad sas token which was previously generated. Hence the second one is an Unauthorized error due to an expired sas token. We may need to think about regenerating the sas token in this case.

**Comment by robbinvandamme** [comment]
@olivakar This will be an issue for many IoTDevices. Do we need to implement something that monitors the IoTHubClientDevice object to check if it is still connected or that it is able to setup a connection and if it fails, create a new object or manually try to reconnect?
 
I thought we could call "await connect()" and then an error is immediately raised when something critical is detected (an invalid connection_string for example, or if it got into an unrecoverable state).
And for the normal cases, "await connect()" could also return immediately. From then on the IoTHubDeviceClient keeps trying to establish a connection. Connection should succeed in the retry loop when system time gets set correctly or when internet connection comes up. This way the SDK users don't need to build something extra around the IoTHubClientDevice to keep the device connected as much as possible after they already called connect(). Is this the goal? Or will we need to build some extra checks/monitors around the IoTHubClientDevice?

**Comment by olivakar** [comment]
Connection generally succeeds in the retry loop when the disconnection has taken place due internet being off and would succeed if internet comes on.

However in this specific scenario, since the times mismatch the original authentication token is not valid. Hence the connection does not succeed even if the time becomes correct as the authentication is always refused.

In the current implementation since we are not generating the sas token on every connection attempt, for the time being you can build something to help solve the problem. 

But eventually we are thinking to include the functionality to regenerate new tokens under certain circumstances. I am not sure exactly when this will be released.

**Comment by olivakar** [comment]
There is a new release which should fail the connect in case of the above error.

**Comment by az-iot-builder-01** [comment]
@robbinvandamme, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
