### ISSUE TITLE
Sample: provision_x509.py

### ISSUE THREAD

**Issue by elvirus839** [Azure/azure-iot-sdk-python#543]
Hi guys, I have been trying to get the python sample "provision_x509.py" to connect through a group enrollment I created on my azure account, but I get the following error when trying to run  the code:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\azure\iot\device\common\pipeline\pipeline_stages_base.py", line 102, in run_op
    self._run_op(op)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\azure\iot\device\common\pipeline\pipeline_thread.py", line 198, in wrapper
    return func(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\azure\iot\device\common\pipeline\pipeline_stages_mqtt.py", line 127, in _run_op
    proxy_options=self.pipeline_root.pipeline_configuration.proxy_options,
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\azure\iot\device\common\mqtt_transport.py", line 133, in __init__
    self._mqtt_client = self._create_mqtt_client()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\azure\iot\device\common\mqtt_transport.py", line 169, in _create_mqtt_client
    ssl_context = self._create_ssl_context()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\azure\iot\device\common\mqtt_transport.py", line 337, in _create_ssl_context
    self._x509_cert.pass_phrase,

FileNotFoundError: [Errno 2] No such file or directory
SetMQTTConnectionArgsOperation: completing with error [Errno 2] No such file or directory
SetProvisioningClientConnectionArgsOperation: completing with error [Errno 2] No such file or directory
SetX509SecurityClientOperation: completing with error [Errno 2] No such file or directory
Callback completed with error [Errno 2] No such file or directory
NoneType: None

NOTE: I do create the env variables before calling the script.
I am using:
Python 3.7.5
azure-iot-device==2.1.1
azure-core==1.3.0

**Comment by olivakar** [comment]
Hi, I tried the sample and it is working.

Could you tell me your certificate steps ? 

-  like the one u verified
- the one u used to create the enrollment

What was your registration id in the sample equal to the common name of the device certificate that you had in group enrollment ?

**Comment by elvirus839** [comment]
Hi, to create the certificate I followed the steps in here: https://github.com/Azure/azure-iot-sdk-c/blob/master/tools/CACertificates/CACertificateOverview.md.

- I think the registration id was "mydevice"

Also I tried the C# version of the sdk with the same certificate and it worked fine.

**Comment by olivakar** [comment]
What type of group enrollment did you create ?

- Ca certificate type 
- Intermediate certificate type

**Comment by elvirus839** [comment]
Here are the details of my certificate:
![image](https://user-images.githubusercontent.com/5313106/80190538-c32a0400-8614-11ea-92f2-2ef4e9f74407.png)

**Comment by olivakar** [comment]
In this scenario , the root CA certificate has gone through proof of possession. 

So while running the device sample did you send the chain of the above device certificate appended by all the intermediate certificates till the root ?

**Comment by elvirus839** [comment]
Hey, I don't really get your question! sorry I am new to CA certificates. But what I added into the code was the content of mydevice-private.pem and mydevice-public.pem!

**Comment by olivakar** [comment]
There are couple of assumptions I am making here based on what you told me. Please let me know if I am incorrect in any of the these.

Since you created a `group_enrollment` with a `CA certificate` you must have gone through proof of possession of the root CA. Otherwise the root certificate is not shown on the drop down list while creating group enrollment. This verification is also a part of the script you followed. 

So my question to you is how many certificates do you have in your chain ? I am assuming 3 since the script you followed creates the following 3. 

1. The root that you had verified with DPS
2. The intermediate
3. The device certificate which you provided screenshot.

The sample you are trying to run wants the file path of your device certificate **ideally**.

Since you have verified the root certificate and created the group enrollment with the root CA, the group enrollment cannot just deal with the device cert only as it needs to build the chain to verify with the root CA. 

For building the chain , your device certificate must be **appended** by the intermediate and this concatenated pem file **Path** must be supplied to the sample. In the following sample code snippet

```
x509 = X509(
    cert_file=os.getenv("X509_CERT_FILE"),
    key_file=os.getenv("X509_KEY_FILE"),
    pass_phrase=os.getenv("PASS_PHRASE"),
)
```

`X509_CERT_FILE` =  **Path** to the file containing device certificate content appended with intermediate certificate content
`X509_KEY_FILE` = **Path** to file containing the device key

Additionally the following variable value is extremely important

`registration_id = os.getenv("DPS_X509_REGISTRATION_ID")` should be same as the common name of the device certificate. From your screen shot it seems to be `mydevice`.

**Comment by elvirus839** [comment]
Hey, I got it to work, it turns out I had the content of the certificates instead of the path to the file in code. I was looking at [this](https://docs.microsoft.com/en-us/azure/iot-dps/tutorial-group-enrollments) tutorial in Java where they implemented that way, so I assumed it would be the same for python. 
Thanks for the help. 
Maybe its a good idea to have the error message be more informative.

**Comment by az-iot-builder-01** [comment]
@elvirus839, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
