### ISSUE TITLE
How device will get to know if i disable it from Azure iot hub UI?

### ISSUE THREAD

**Issue by popdk** [Azure/azure-iot-sdk-python#60]
- **OS and version used:** <VERSION> 

- **Python runtime used:** <VERSION> 

- **SDK version used:** <VERSION> 

# Description of the issue:
Is there any callbacks or any event trigger when i disable device from Azure iot hub UI and from device side know, So i can take appropriate action on my physical device.

# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by olivierbloch** [comment]
Hi @popdk , there is no message or notification that goes down to the device when it is deactivated at the IoT Hub service level. This is by design as we actually don't want a device that has been compromised to receive anything from IoT Hub.
Now, if you want to deactivate a device as part of your scenario, then you have several options to notify the device (yourself, and based on your own scenario) leveraging C2D messages, Direct Methods or Device Twins before deactivating the device in the back end.
Also if you deactivate a device that is offline, next time it will try to connect, it will get an authentication error which you can deal with in your code on the device side.
