### ISSUE TITLE
[Technical Question] How to register for "twinChangeEvents"?

### ISSUE THREAD

**Issue by mebster2** [Azure/azure-iot-sdk-python#708]
Dear Ladies and Gentleman,

I would like to register an IoT device for twinChangeEvents on the IoTHub. So that I am immediately notified when configuration changes in the reported twin have been adopted by the desired twin. I tried to do this with D2C (method=twinChangeEvents ) and C2D (twinChangeEventsCallback), but it seems not to be the appropriate way. What is the recommended strategy to do this?

Thank you already in advance.
Yours sincerly,
Marco Ebster

AB#8824649

**Comment by elhorton** [comment]
Hi @mebster2 , thanks for reaching out. Could you please elaborate on your scenario a little? What are you trying to achieve with device twins?

You say "when configuration changes in the reported twin have been adopted by the desired twin"-- this is application code that a developer would write to respond to a change in the desired twin (for example, you request the device fan speed to be at a higher value, so the application code increases the fan speed). I'm not sure I understand your question correctly, so hoping that I'll get it if you can explain a little more about your code.

**Comment by BertKleewein** [comment]
@mebster2, I'm a little confused by your question.  When you say

>> when configuration changes in the reported twin have been adopted by the desired twin. 

I get stuck on the phrase "adopted by the desired twin" because there's nothing built into the service that connects the reported property values with desired property values.  If you say "adopted by the device twin", it makes more sense.

If you want to get notified when a device changes the reported properties, you need to define a route on your IoTHub instance.  You can find some documentation [here](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-device-twins).

An easy way to see this in action is to go to the portal page for your IoTHub instance, then select "Message routing" from the leftmost pane.  Add a new route with the following properties:
* endpoint: `events`
* data source: `Device Twin Change Events`

Also, give it a name, enable it, and leave the routing query to `true` (it will put the number `1` in line with `this`.  ignore the number.)

Then you can monitor events using the tool of your choice.  I prefer the [Azure CLI](https://docs.microsoft.com/en-us/cli/azure/what-is-azure-cli): 
```
az iot hub monitor-events --login ${CONNECTION_STRING}
``` 
If you do this, you should see events when a device changes reported properties.

**Comment by mebster2** [comment]
Hi,

I would like to listen for desired twin change events. For example I have an IoT device, which triggers some configuration changes (e.g. modify output volume). This results in an new desired config version.

My question is, what is the best strategy to get notified on client (IoT device) side, if such a new desired config version appears?

I played a little bit with the following example. It is basically working, but it seems to be decprecated.
https://github.com/Azure/azure-iot-sdk-python-preview/blob/master/azure-iot-device/samples/advanced-hub-scenarios/receive_twin_desired_properties_patch.py

Additionally it seems not to be the most ellegant way for my test case. I would like to run a test, with on IoT device. It would be optimal if i could register this device for upcoming desired twin change events and get notified after every change. If I would use the example above I would need for example two threads. One desired twin change listener and the test runner itself. Because otherwise the receive_twin_desired_properties_patch function would block the whole run and wait for a desired config change.

Do know know a better solution for my use case?

LG!
Marco Ebster

**Comment by mebster2** [comment]
Issue can be closed. Solved the problem!
Thank you for your help.

**Comment by elhorton** [comment]
Hi @mebster2 , glad you solved the problem! What was your solution? It would be great to share your learnings with the community and improve this project.

**Comment by az-iot-builder-01** [comment]
@BertKleewein, @mebster2, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
