### ISSUE TITLE
on_method_request_received property not documented

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-iot-sdk-python#725]
@boazeg commented on [Mon Jan 18 2021](https://github.com/Azure/azure-sdk-for-python/issues/16224)

As part of the receive_method_request method documentation the following comment appears:
Deprecated since version 2.3.0: We recommend that you use the .on_method_request_received property to set a handler instead

However, there is no documentation of this property (.on_method_request_received) on this page, no link to another documentation page, no sample code to demonstrate its usage and it also does not seem to work at runtime in our custom module - we can set it OK but not receive any callback when a method is called (trying to use receive_method_request() method works well in the same module).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 178e6ad2-a925-7c36-7600-5c8160e8d81c
* Version Independent ID: 327ccd4e-78fb-f87d-9d0f-9b9ff6afc33c
* Content: [azure.iot.device.aio.IoTHubModuleClient class](https://docs.microsoft.com/en-us/python/api/azure-iot-device/azure.iot.device.aio.iothubmoduleclient?view=azure-python)
* Content Source: [docs-ref-autogen/azure-iot-device/azure.iot.device.aio.IoTHubModuleClient.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-iot-device/azure.iot.device.aio.IoTHubModuleClient.yml)
* Product: **azure-iot**
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by elhorton** [comment]
Hi @boazeg , thanks for filing this. We will take a look at this documentation & content gap next week and update you here.

**Comment by cartertinney** [comment]
Due to the fractured inheritance hierarchy of our class definitions, these handlers are defined in a different class from a different module, which is why you aren't seeing them.

Our [samples folder](https://github.com/Azure/azure-iot-sdk-python/tree/master/azure-iot-device/samples) contains examples showing the usage of these handlers. The documentation for them can currently be accessed via the python `help` command which shows all documentation for a class (e.g. `help(IoTHubDeviceClient)`)

However, as you point out, there is an issue with the doc generation for our online resources not picking up these (and other) properties. I'm investigating a way that we can address that now.

**Comment by boazeg** [comment]
@cartertinney Please note that the bug was actually opened on the documentation of IoTHub**Module**Client and not IoTHub**Device**Client. I was aware of the Device client samples, but there are no Module client samples (as far as I can tell).
In my case, I had a runtime version issue that caused the callback not to be called, but nevertheless, not having a sample, and not seeing this callback in the IoTHubDeviceClient implementation did not help...

**Comment by cartertinney** [comment]
I will see about adding a module specific sample, however the same principle applies regarding documentation - you can see the correct documentation using the python `help` command (e.g. `help(IoTHubModuleClient)`.

Fixes for online web documentation surrounding handlers will be included as part of the next release.
