### ISSUE TITLE
[Technical Question] Device Library for gateways?

### ISSUE THREAD

**Issue by dberenguer** [Azure/azure-iot-sdk-python#804]
Is the Device Library indicated to run in gateways? We need to connect a LoRaWAN network containing some hundreds of devices to Azure IoT HUB but I have the impression that this library is not made for this purpose.

I know there is the IoT Edge device that can be run as a gateway, but our gateway is not really on the edge but in the cloud and I wanted something more straightforward than the IoT Edge approach, requiring us to deploy modules in containers.

Thanks in advance.

**Comment by cartertinney** [comment]
We support using connection strings that have a GatewayHostName property specifying a gateway, and will use that information when connecting to the Hub.

Does that sound sufficient for your scenario?

**Comment by dberenguer** [comment]
Thanks Carter,

I didn't know there was such gateway property. The most important thing for a cloud gateway is to be able to send messages on behalf of other lower devices so we need multiple devices on IoT HUB to be updated from a single gateway. I was hoping to do so with this SDK by means of AMQP transmissions but now it looks like MQTT is the default technology used by this SDK. Am I right?

**Comment by cartertinney** [comment]
That is correct, we do not support AMQP, however I believe MQTT should be sufficient for your purposes so long as you have a connection string for your device that includes a GatewayHostName

**Comment by dberenguer** [comment]
Thanks Carter,

1. Documentation regarding this approach seems to be pointing to the use of an IoT Edge device as a gateway, but we want to host the gateway in the cloud, not in the Edge and avoid the hardness and limitations about deploying all the Edge stuff.

2. Since AMQP is not supported by this SDK, our gateway should create and maintain as many MQTT connections to the IoT HUB as devices connected to the gateway. This is not an option when we have hundreds of connections to maintain.

The issue is that MQTT can not be used in Azure IoT HUB in multiplexing scenarios (multiple devices being reported through a single connection). All the docs seem to be pointing to the use of AMQP in this case, and this SDK does not support AMQP. On the other hand, the Java and C Device SDK's are indeed supporting AMQP and device multiplexing so I think we are moving to one of those SDK's. Or am I missing something?

**Comment by cartertinney** [comment]
@dberenguer 

While the documentation does focus on an Edge scenario, as long as you have a GatewayHostName in your Connection String, it should work regardless.

As for multiplexing, I will have to look into that and get back to you.

**Comment by BertKleewein** [comment]
@cartertinney and @dberenguer  - The `GatewayHostName` field is not what you're looking for.  You use `GatewayHostName` when you want to _talk to_ a gateway.  This conversation is about _being_ a gateway.

@dberenguer - your understanding of multiplexing is correct.  MQTT does not support multiplexing.  For that, you would need to use AMQP, which does support multiplexing.  This library does not support AMQP, so you appear to be at a dead end.

The term that we use for this is "Identity Translation".  You can find some documentation here: https://docs.microsoft.com/en-us/azure/iot-edge/iot-edge-as-gateway?view=iotedge-2018-06#translation-gateways

IoT Edge has some functionality in preview to support this, but, because it's in preview, it's not particularly well documented or supported.  It's also expected to change before being released as an official feature.  Details are here: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-publish-subscribe?view=iotedge-2020-11

IoTHub may also be supporting the notion of identity translation in some future release.

**Comment by dberenguer** [comment]
Thanks @BertKleewein and @cartertinney for your help.

For other people wanting to implement gateways, the C and Java SDK's do support AMQP and multiplexing. I don't know about the Node.js version though.
