### ISSUE TITLE
Using SDK fails with error: ImportError: libboost_python-py34.so.1.54.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by srids** [Azure/azure-iot-sdk-python#81]
- **OS and version used:** Debian GNU/Linux 8 (jessie) in a Docker container based off of python:3-slim image 

- **Python runtime used:** Python 3.6.3 

- **SDK version used:** azure-iothub-device-client (1.1.25.0) azure-iothub-service-client (1.1.0.17) 

# Description of the issue:

Installation was performed based off of the above environment as:
apt-get install libpython3-dev
apt-get install libboost-python-dev
pip3 install azure-iothub-device-client==1.1.25.0
pip3 install azure-iothub-service-client==1.1.0.17

Once after that, using either the device SDK or service SDK by importing in Python it fails with error: ImportError: libboost_python-py34.so.1.54.0: cannot open shared object file: No such file or directory

Effectively cannot use Python SDK.

# Code sample exhibiting the issue:

from iothub_service_client import IoTHubRegistryManager, IoTHubRegistryManagerAuthMethod
or
from iothub_client import IoTHubMessageDispositionResult

# Console log of the issue:

From the Python console:
>>> from iothub_client import IoTHubMessageDispositionResult
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/iothub_client/__init__.py", line 1, in <module>
    from .iothub_client import *
ImportError: libboost_python-py34.so.1.54.0: cannot open shared object file: No such file or directory

**Comment by zolvarga** [comment]
@srids 

Thanks for using our Python SDK and reporting this issue.
We are looking at the issue and will get back to you.

Best Regards,
Zoltan

**Comment by koalalorenzo** [comment]
Same error here! What was the way to solve this? _seems like_ it is a stupid/easy-to-fix import error. News?

**Comment by syedhassaanahmed** [comment]
+1

**Comment by wictorwilen** [comment]
I can also report this; on a Raspberry Pi

**Comment by koalalorenzo** [comment]
This is dumb, a simple test in a pipeline (what about full CI/CD?) would solve the problem for both python 2 and python 3. Switching to Kafka just because we can't solve it and we are loosing time. 😢

**Comment by digimaun** [comment]
The error is complaining that you don't have the right dependent libraries in your environment. You need boost 1.54 installed, specifically libboost-python1.54-dev, this comes with the required shared objects.

**Comment by srids** [comment]
I think that is the problem - there is no libboost-python1.54-dev package but libboost-python1.55-dev (current/default for libboost-python-dev). Error: Package 'libboost-python1.54-dev' has no installation candidate

**Comment by digimaun** [comment]
Have you tried getting the package from  [launchpad](https://launchpad.net/ubuntu/trusty/+package/libboost1.54-all-dev) and using dpkg to install?

**Comment by koalalorenzo** [comment]
what about macOS and Docker alpine?

**Comment by srids** [comment]
with the given env reported in this issue (Debian GNU/Linux 8 (jessie)), the package libboost-python1.54-dev is not available.
check:
https://packages.debian.org/search?keywords=libboost-python1.54-dev
https://packages.debian.org/search?keywords=libboost-python1.55-dev

i guess, it makes sense to have this SDK to be compatible across different or multiple libboost versions.

**Comment by zolvarga** [comment]
@srids 

I agree with you. Debian is recently added to the supported OS matrix. We created a work item to investigate the issue. 

Best Regards,
Zoltan

**Comment by ggoglodze** [comment]
Same issue on Ubuntu 16.04
There is NO version libboost-python**1.54** available
```
root@usiot:~# apt-cache search libboost|grep libboost-pyt
libboost-python-dev - Boost.Python Library development files (default version)
libboost-python1.58-dev - Boost.Python Library development files
libboost-python1.58.0 - Boost.Python Library

```

**Comment by udayds** [comment]
Hi Zoltan. Can you please let know by when can we expect this issue to be resolved.

Thanks,
Uday

**Comment by toddysm** [comment]
Hi @zolvarga - any update on this? I am getting 
`Traceback (most recent call last):
  File "create_device_id.py", line 4, in <module>
    from iothub_service_client import IoTHubRegistryManager, IoTHubRegistryManagerAuthMethod
  File "/usr/local/lib/python2.7/dist-packages/iothub_service_client/__init__.py", line 1, in <module>
    from .iothub_service_client import *
ImportError: libboost_python-py27.so.1.55.0: cannot open shared object file: No such file or directory`

and the lowest version of libboost I can install is 1.58. At this point, the library is unusable on Raspbian.

**Comment by SummerSun** [comment]
+1

Same issue in Raspbian with python 2.7.13

**Comment by digimaun** [comment]
@ggoglodze You can use Ubuntu Trusty packages in Xenial to get around your issue. [Here ](https://digimaun.github.io/cloudsauce/2017/09/25/ubuntu-xenial-leveraging-trusty-packages/)is a reference that might be useful.

**Comment by Georg-W** [comment]
+1
Same issue using ubuntu bash on windows with the simulated Device example.

**Comment by digimaun** [comment]
Until an update has been released, as a workaround for Ubuntu 16.04+ LTS, you can try installing boost from the Ubuntu Trusty repos. 

Example script
```
echo "deb http://archive.ubuntu.com/ubuntu/ trusty main universe" | tee -a /etc/apt/sources.list
echo "deb http://archive.ubuntu.com/ubuntu/ trusty-updates main universe" | tee -a /etc/apt/sources.list
apt-get update
apt-get install -y libcurl4-openssl-dev
apt-get install -y --allow-downgrades libopenmpi-dev=1.6.5-8 openmpi-bin=1.6.5-8 openmpi-common=1.6.5-8
apt-get install -y --allow-downgrades libboost1.54-all-dev
```

**Comment by Alex-Danielsen** [comment]
@digimaun I tried your work around, including using aptitude to manage dependency conflicts. But aptitude is wanting me to remove ros-kinetic, in order to ge tthe libboost libraries from trusty. And the project I need libboost for runs on ros. Do you have any suggestions?

**Comment by digimaun** [comment]
@Alex-Danielsen If ros doesn't support the older boost then I don't recommend mixing versions. Unfortunately I think your best bet is to recompile this library with a newer boost installed. It should work with boost 1.58 (like if you tried compiling on 16.04 LTS).

**Comment by ggoglodze** [comment]
Guys, I dont see libboost issue any more. I install fresh Uuntu 16 and then followed installation steps. all the client/device samples worked for both python2 and 3

**Comment by zolvarga** [comment]
Thanks @ggoglodze to confirm this is a Linux installation issue.

Closing this as it resolved. 

Best Regards,
Zoltan

**Comment by MrDadaGuy** [comment]
Still an issue on Raspbian...

**Comment by zaheer308** [comment]
its still an issue on Raspbian running on raspberry pi 3, urgent help needed

**Comment by Prasad491** [comment]
root@raspberrypi:/home/pi/iot-hub-python-raspberrypi-client-app# python iothub_messaging_sample.py
Traceback (most recent call last):
  File "iothub_messaging_sample.py", line 7, in <module>
    import iothub_service_client
  File "/home/pi/iot-hub-python-raspberrypi-client-app/iothub_service_client/__init__.py", line 1, in <module>
    from .iothub_service_client import *
ImportError: libboost_python-py27.so.1.55.0: cannot open shared object file: No such file or directory


May I know why this error persists even though i have installed iothub_service_client?
Any help is appreciated.......

**Comment by wladneto** [comment]
I have the same problem like @Prasad491

**Comment by zaheer308** [comment]
@wladneto , @Prasad491  here is the solution posted by @sergiomfsilva 

Hi,

feedback about installing from scratch

Enviroment
OS and version used: Linux raspberrypi 4.14.30-v7+ #1102 SMP Mon Mar 26 16:45:49 BST 2018 armv7l GNU/Linux

Python runtime used: Python 3.5.3

SDK version used: 1.3.1

Workaround steps used
Get images and prepare to do the work
get last Rasbian Lite Image
flash microSD card for Raspberry Pi3
boot with raspberry pi
login with pi user
make the command
sudo su
go to root folder
cd /root
Update the system and make some time checks
Do the next commands

apt-get update && apt-get upgrade
apt-get install ntp
Check the RPI date with the command

date

After date ok all its ready

Note: Configure ntp.conf file if date issues found.

Install required packages and review the error reported
Install required packages
apt-get install -y git cmake build-essential curl libcurl4-openssl-dev libssl-dev uuid-dev python3-pip

Clone SDK
git clone --recursive https://github.com/Azure/azure-iot-sdk-python.git

Install device client package using pip3
pip3 install azure-iothub-device-client

Go to samples folder
cd azure-iot-sdk-python/device/samples/

Run the sample code
python3 iothub_client_sample.py

The error must be the same

Traceback (most recent call last):
  File "iothub_client_sample.py", line 10, in <module>
    import iothub_client
  File "/usr/local/lib/python3.5/dist-packages/iothub_client/__init__.py", line 1, in <module>
    from .iothub_client import *
ImportError: libboost_python-py34.so.1.55.0: cannot open shared object file: No such file or directory

Build new libraries and apply it
Go to building folder for linux
cd /root/azure-iot-sdk-python/build_all/linux

Run Setup
./setup.sh --python-version 3.5

Replace openssl dev with gnutls dev already reported like solution for a curl out of memory issue

apt remove libcurl4-openssl-dev
apt install libcurl4-gnutls-dev
build libraries
./build.sh --build-python 3.5

Go to root folder
cd /root

Move created library to python iothub_client path
mv azure-iot-sdk-python/device/samples/iothub_client.so /usr/local/lib/python3.5/dist-packages/iothub_client/iothub_client.so

Go to samples folder
cd azure-iot-sdk-python/device/samples/

Run the sample code
python3 iothub_client_sample.py

Conclusion
This solve the issue found and works in the raspberry.
This did not solve this issue because it is related with the pip package. To solve a new pip package with library and python version updated.
