### ISSUE TITLE
Python 3.6 support when building SDK

### ISSUE THREAD

**Issue by dariuszparys** [Azure/azure-iot-sdk-python#83]
- Ubuntu 17.10
- Python 3.6.3
- Latest SDK https://github.com/Azure/azure-iot-sdk-python

I tried to build the SDK with Python 3.6.3 which seems to be supported as stated in the docs but after executing 

```
➜  linux git:(master) ./build.sh --build-python 3.6
Supported python versions are 2.7, 3.4 or 3.5
```

the message tells that it isn't. Could you give feedback if 3.6 should work?

**Comment by zolvarga** [comment]
@dariuszparys,

Thanks for using our SDKs. You find a bug in the build script, which will be fixed in our next release.
Meanwhile, to unblock yourself, please change the line 73 in:
..\azure-iot-sdk-python\c\build_all\linux\build.sh

from
        if [ $build_python != "2.7" ] && [ $build_python != "3.4" ] && [ $build_python != "3.5" ]
to 
        if [ $build_python != "2.7" ] && [ $build_python != "3.4" ] && [ $build_python != "3.5" ] && [$build_python != "3.6"]

The build should succeed with this change. 
FYI - we are regularly building the Python SDK with 3.6.

Best Regards,
Zoltan

**Comment by zolvarga** [comment]
Closing as fix is provided and also checked in.
