### ISSUE TITLE
Provisioning Client timeout after failed Authentication Exception

### ISSUE THREAD

**Issue by jonathon793** [Azure/azure-iot-sdk-python#915]
# Context
- Ubuntu Core
- Python 3.8
- azure-iot-device==2.9.0

## Description of the issue

I'm working on a device which does not have an RTC, thus, when it first starts up, we do not have correct time.
As a result, if we attempt to Provision with a certificate after we connect to the cloud, but before NTP has synced time, we get a `exceptions.TlsExchangeAuthError`, which is expected since the certificate's time range will not be acceptable yet.
however, we try to connect again after time syncs, and we get a different exception: 
`ClientError('Unexpected failure') caused by ServiceError('Operation timed out before provisioning service could respond for register operation')`
we continue to receive this exception until we restart our application.
this began to occur when we implemented the fix recommended here: https://github.com/Azure/azure-iot-sdk-python/issues/899

## Console log of the issue
[provisioningTimeout.log](https://github.com/Azure/azure-iot-sdk-python/files/7669555/provisioningTimeout.log)

**Comment by cartertinney** [comment]
@jonathon793 

I have some ideas about what might be causing this, but I need a bit of help to reproduce this issue - it seems that you're using X509 certificates now (wheras in #899 you were using symmetric key auth). Are there any other auth or config changes you've made? Also, what exactly is the reason the certs are failing due to lack of time sync? Is the certificate appearing to have already expired? Not become valid yet? Something else?

**Comment by jonathon793** [comment]
that's the only configuration change, according to the log the cert is not valid yet:

> Callback completed with error TlsExchangeAuthError(None) caused by SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: **certificate is not yet valid**

**Comment by jonathon793** [comment]
@cartertinney , were my answers sufficient? any other information that could be helpful?

**Comment by cartertinney** [comment]
@jonathon793 

I have been able to repro the issue, working on figuring out what the issue is now. Will hopefully have an update for you soon.

**Comment by jonathon793** [comment]
@cartertinney , any update yet?

**Comment by cartertinney** [comment]
@jonathon793

I think I've found the issue - certificates can only be loaded once, and that happens at client creation, when your clock has not yet synced time with the NTP.

An assumption in the client design is that once you create the client, nothing should be changing. In this case, because the certificates aren't valid when you create the client, it makes the client unusable. This is why before when you were creating multiple clients you never had an issue.

I'm going to keep looking at potential ways we can mitigate or at least more clearly report the issue in errors, but for now (and potentially for the foreseeable future) I have two possible mitigation strategies:

1) Make sure that your device has done a NTP sync before you create the client in your application logic. This is probably the easiest option.

2) Alternatively, when the client fails due to this certificate issue, you can shutdown the client, and then create a new instance of it (assuming NTP sync has occurred in the meantime. This suggestion is somewhat tricky, because currently we only raise a generic `ClientError`. I'm going to see about trying to improve this in the future, but for now as a workaround you can check the error's `.__cause__` attribute to find out the deeper cause, and in the case of your certificate verification problem you should see it be of type `TlsExchangeAuthError` from the `azure.iot.device.iothub.pipeline.exceptions` module. Note that this is an internal module not intended for customer access, and as such, may be subject to change in future releases.

**Comment by cartertinney** [comment]
@jonathon793 

Were the above options sufficient to mitigate your issue?

**Comment by jonathon793** [comment]
@cartertinney , yes.  thank you very much
