### ISSUE TITLE
[Technical Question] iot-hub-device "connected" member and its behaviour.

### ISSUE THREAD

**Issue by robbinvandamme** [Azure/azure-iot-sdk-python#923]
Hi,

I'm using:
azure-iot-device==2.9.0

In my application I have a job monitoring the iot-hub-device his connection state via the read-only "connected" member.
I monitor this state every second, when changed, we emit an event.
On a number of devices I see that they often send me a disconnected event and one second later a connected event.
So this member "connected" returns False for at maximum one second, because the next iteration it's connected again.

I would like to understand why this "connected" state changes for at maximum one second to disconnected and immediately again to connected.
Is it because of the token refresh, but this should not change the "connected" state during a refresh I think?
On some devices it could be stable to 8hours, other devices send me these events every hour.
Are there other reasons?

As you can see in the image, we get disconnected and one second later a connected event. Almost always one hour in between the 2 disconnects. Token refresh issue?

![image](https://user-images.githubusercontent.com/13780546/146397556-bf169588-e2fe-4ebd-b59a-b1523caebb36.png)

Kind regards,

Robbin

**Comment by cartertinney** [comment]
@robbinvandamme 

Yes, it's due to token refresh. Refreshing the token requires us to disconnect and reconnect the client, thus the connection state will briefly change - we don't hide this aspect of the functionality by suppressing the disconnection, after all, there could be failures during reconnect, etc.

If you're trying to monitor the state, I also might recommend using the `.on_connection_state_change` handler so you don't have to monitor the state every second.

**Comment by robbinvandamme** [comment]
@cartertinney 
Thx for you quick reply!

Yes I'm aware of the .on_connection_state_change functionality, but the job running every second will still be there for other reasons and read the "connected" member is very cheap.

However, I could stop reading the "connected" member and use the .on_connection_state_change event if it doesn't get emitted on a token refresh. 
If .on_connection_state_change is also emitted every token refresh I'll need to work around it and ignore the state changes if they are less then 5sec apart for example.

I still find it a bit strange the state is changed and emitted on a token refresh. You could also only emit a disconnect event if the token refresh fails?

**Comment by cartertinney** [comment]
@robinvandamme

Ultimately, our current design philosophy is not to try and hide what's going between the Device and the IoTHub. SAS Token renewal will cause a disconnect, and then a connect.

These disconnect/connects show up in IoTHub logs, so we want to be transparent about the behavior in order to prevent confusion.

**Comment by robbinvandamme** [comment]
@cartertinney 
OK, I understand.

But the drawback is that, we as user of the sdk, need to figure out our-self if it was just a quick reconnect due to a token refresh or a real disconnect. I can image that there are a lot of cases where we don't want to start the "disconnect" logic or procedure due to a token refresh, because in 99% of the time we will only be disconnected for 1sec (or even less than one second.)

And one other thing:
lets say we trigger a direct method over the iot-hub towards the device at the exact same time of the token refresh.
That direct method call will fail or is that robust enough to deal with these token refreshes. I would expect it will not fail..?

**Comment by cartertinney** [comment]
@robbinvandamme 

There is enough robustness to deal with that scenario. The method call will either finish before the token refresh happens, or wait until after token refresh has finished. If the token refresh fails to reconnect due to network failure, there may also be a failure on the direct method call due to the same failure.

If you're looking for a way to catch when there is some kind of failure rather than disconnect, you could try the .on_background_exception handler. However if you're using the `connection_retry` option (on by default) be aware that the client is going to repeatedly try to re-establish the connection in the event of failure, and so you may see multiple failures from multiple auto-reconnection attempts

**Comment by robbinvandamme** [comment]
@cartertinney thx!

**Comment by robbinvandamme** [comment]
@cartertinney 
Is it allowed to call connect() when using the connection_retry option, or will this cause issues?
If this causes issues, is there a way to know if auto-reconnect is running?
